baseURL = "https://github.com/wurslu/blog"
languageCode = "zh-cn"
title = "urlu"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  # 中文界面元素
  [params.label]
    text = "首页"
    icon = "/apple-touch-icon.png"
    iconHeight = 35

# 中文菜单
[[menu.main]]
name = "首页"
url = "/"
weight = 10

[[menu.main]]
name = "文章"
url = "/posts/"
weight = 20

[[menu.main]]
name = "标签"
url = "/tags/"
weight = 30