baseURL = 'https://blog.urlu.cool/blog'
languageCode = 'zh-cn'
title = 'Urlu Blog'
theme = 'PaperMod'

[params]
defaultTheme = 'auto'
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 10
  
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 20
  
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 30
  
  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 40
  
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 50