baseURL = 'https://wurslu.github.io/blog'
languageCode = 'zh-cn'
title = 'URLU Blog'
theme = 'PaperMod'

[params]
defaultTheme = 'auto'
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true